// ===========================================================================
// Generate the reference-data SQL for a permission-catalogue migration.
//
//   npx ts-node scripts/generate-catalogue-migration.ts            # print
//   npx ts-node scripts/generate-catalogue-migration.ts --check    # verify
//
// The migration SQL is an **immutable historical snapshot**, not a second
// source of authority. It is produced mechanically from
// `src/rbac/role-permissions.ts` so that nobody ever hand-maintains a second
// list of permission keys — a hand-maintained duplicate of exactly this kind is
// what let registration ship without permissions in the first place.
//
// `--check` regenerates the body and compares it to what is committed, so the
// snapshot cannot drift from the canonical source without failing the build.
//
// **Adding a permission later means a NEW migration, never editing this one.**
// An applied migration is history; rewriting it would leave every database that
// already ran it silently different from the file that claims to describe it.
// ===========================================================================

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { PERMISSIONS } from '../src/rbac/role-permissions';

export const CATALOGUE_MIGRATION = '0059_permission_catalogue_reference_data';

/** MySQL string literal. Labels are our own text, but never build SQL by trust. */
function sqlString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "''")}'`;
}

/**
 * The reference-data statement.
 *
 * Follows the convention already used by 0044/0047/0049/0050: a `VALUES`-shaped
 * subquery filtered by a correlated `NOT EXISTS`, so
 *
 *  - a key that is already present is left completely alone — no UPDATE, no
 *    REPLACE, no delete-and-reinsert, so existing ids, labels and any row
 *    metadata survive untouched;
 *  - a key that is missing is inserted;
 *  - applying it to a database that already holds all 61 keys writes nothing.
 *
 * Deliberately NOT `INSERT IGNORE`, which would also swallow a genuine error —
 * a truncated label under strict mode, a broken constraint — and leave the
 * catalogue quietly short. An unexpected conflict must fail loudly.
 *
 * Ids are generated by MySQL at apply time rather than baked in, matching the
 * existing migrations. Reference rows are identified by `key`, which is unique;
 * the id is never a cross-environment contract.
 */
export function buildCatalogueSql(): string {
  const rows = PERMISSIONS.map(
    (p, i) =>
      (i === 0
        ? "  SELECT UNHEX(REPLACE(UUID(), '-', '')) AS id, "
        : "  UNION ALL SELECT UNHEX(REPLACE(UUID(), '-', '')), ") +
      (i === 0
        ? `${sqlString(p.key)} AS k, ${sqlString(p.label)} AS l`
        : `${sqlString(p.key)}, ${sqlString(p.label)}`),
  ).join('\n');

  return `INSERT INTO \`permissions\` (\`id\`, \`key\`, \`label\`)
SELECT * FROM (
${rows}
) AS want
WHERE NOT EXISTS (SELECT 1 FROM \`permissions\` p WHERE p.\`key\` = want.k);`;
}

/** The key set this migration is responsible for publishing. */
export function catalogueKeys(): string[] {
  return PERMISSIONS.map((p) => p.key).sort();
}

function committedSql(): string {
  return readFileSync(
    join(__dirname, '..', 'prisma', 'migrations', CATALOGUE_MIGRATION, 'migration.sql'),
    'utf8',
  );
}

/**
 * Does the committed migration still publish exactly the canonical key set?
 *
 * Compares KEYS and LABELS, not whole text: the generated ids differ on every
 * call by design, so a byte comparison would always fail.
 */
export function checkCommittedMigration(): { ok: boolean; missing: string[]; extra: string[] } {
  const sql = committedSql();
  const inSql = new Set([...sql.matchAll(/'((?:[a-z_]+\.)+[a-z_]+)'/g)].map((m) => m[1]));
  const canonical = new Set(catalogueKeys());

  const missing = [...canonical].filter((k) => !inSql.has(k)).sort();
  const extra = [...inSql].filter((k) => !canonical.has(k)).sort();
  return { ok: missing.length === 0 && extra.length === 0, missing, extra };
}

if (require.main === module) {
  if (process.argv.includes('--check')) {
    const { ok, missing, extra } = checkCommittedMigration();
    console.log(`  ${CATALOGUE_MIGRATION}`);
    console.log(`  canonical keys : ${catalogueKeys().length}`);
    if (missing.length) console.log(`  MISSING from the migration: ${missing.join(', ')}`);
    if (extra.length) console.log(`  NOT canonical, in the migration: ${extra.join(', ')}`);
    console.log(ok ? '  in step with the canonical source ✓' : '  DRIFTED from the canonical source');
    process.exitCode = ok ? 0 : 1;
  } else {
    console.log(buildCatalogueSql());
  }
}
